const SET_GET_PRODUCT_STATUS = "PRODUCT/SET_GET_PRODUCT_STATUS";
const SET_SEARCH_PRODUCT_STATUS = "PRODUCT/SET_SEARCH_PRODUCT_STATUS";
const SET_SHOW_MORE_PRODUCT_STATUS = "PRODUCT/SET_SHOW_MORE_PRODUCT_STATUS";
const SET_PRODUCTS = "PRODUCT/SET_PRODUCTS";

export default {
    SET_GET_PRODUCT_STATUS,
    SET_SEARCH_PRODUCT_STATUS,
    SET_SHOW_MORE_PRODUCT_STATUS,
    SET_PRODUCTS
}